_FILTERS = {
    "vivid": {
        1: {
            "brightness": 0.0,
            "exposure": 0.5,
            "contrast": -0.1,
            "warmth": 0.0,
            "saturation": 0.5,
            "vibrance": 0.2,
            "hue": 0.0,
            "gamma": 1.3,
        },
        2: {
            "brightness": 0.0,
            "exposure": 0.5,
            "contrast": 0.1,
            "warmth": 0.0,
            "saturation": 0.3,
            "vibrance": 0.6,
            "hue": 0.0,
            "gamma": 1.3,
        },
        3: {
            "brightness": 0.0,
            "exposure": 0.2,
            "contrast": -0.1,
            "warmth": 0.4,
            "saturation": 0.5,
            "vibrance": 0.9,
            "hue": 0.0,
            "gamma": 1.3,
        },
    },
    "monochrome": {
        1: {
            "brightness": 0.0,
            "exposure": 0.0,
            "contrast": -0.2,
            "warmth": 0.0,
            "saturation": -1.0,
            "vibrance": 0.0,
            "hue": 0.0,
            "gamma": 1.3,
        },
        2: {
            "brightness": 0.0,
            "exposure": 0.0,
            "contrast": 0.1,
            "warmth": 0.0,
            "saturation": -1.0,
            "vibrance": 0.0,
            "hue": 0.0,
            "gamma": 1.3,
        },
        3: {
            "brightness": -0.1,
            "exposure": 0.9,
            "contrast": 0.0,
            "warmth": 0.0,
            "saturation": -1.0,
            "vibrance": -0.5,
            "hue": 0.0,
            "gamma": 1.3,
        },
    },
    "dramatic": {
        1: {
            "brightness": -0.1,
            "exposure": 0.0,
            "contrast": 0.0,
            "warmth": 0.6,
            "saturation": -0.4,
            "vibrance": -0.5,
            "hue": 0.0,
            "gamma": 1.3,
        },
        2: {
            "brightness": -0.1,
            "exposure": 0.4,
            "contrast": 0.2,
            "warmth": 0.4,
            "saturation": -0.4,
            "vibrance": -0.5,
            "hue": 0.03,
            "gamma": 1.3,
        },
        3: {
            "brightness": -0.1,
            "exposure": 0.4,
            "contrast": 0.1,
            "warmth": 0.6,
            "saturation": -0.2,
            "vibrance": -0.8,
            "hue": 0.02,
            "gamma": 1.3,
        },
    },
}
